# API Worker Configuration
name = "oshieru-api"
main = "apps/api/src/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "oshieru-db"
database_id = "aa4d3b25-215a-48f8-9256-1fe734fa305c"

[[kv_namespaces]]
binding = "KV"
id = "decda47d94434294ad00a6c3b3fe7144"
preview_id = "a40aad0cc123475baccb4f8cd57650ea"

[[services]]
binding = "SCORE_WORKER"
service = "oshieru-score"

# Environment variables
[vars]
ENVIRONMENT = "production" 